name: CI

on:
 push:
  paths:
  - "**.py"
 pull_request:
  paths:
   - "**.py"

jobs:
 lint-isort:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-python@v2
     with:
      python-version: 3.8
   - uses: jamescurtin/isort-action@master
     with:
      configuration: "--check-only --diff --profile black"
 lint-black:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-python@v2
   - uses: psf/black@stable
     with:
      options: ". --check"
 TODO:
  runs-on: "ubuntu-latest"
  steps:
   - uses: "actions/checkout@master"
   - uses: "alstr/todo-to-issue-action@v4.0-alpha"
     with:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}